"""
Local OpenAI-compatible REST API server for Eco-Loop LLM Agent testing on port 8085.
Exposes POST /v1/chat/completions returning structured JSON tool calls.
"""

import json
from http.server import HTTPServer, BaseHTTPRequestHandler
import sys

PORT = 8085


class MockLLMHandler(BaseHTTPRequestHandler):

    def do_POST(self):
        if self.path.startswith("/v1/chat/completions"):
            length = int(self.headers.get("content-length", 0))
            body_bytes = self.rfile.read(length)
            try:
                body = json.loads(body_bytes.decode("utf-8"))
            except Exception:
                body = {}

            messages = body.get("messages", [])
            messages_text = json.dumps(messages)

            if "Tool Result for validate_action" in messages_text:
                # Turn 3: LLM calls apply_setpoints
                response_content = {
                    "thought": "Candidate setpoints passed safety validation. Committing setpoints via apply_setpoints.",
                    "tool_call": {
                        "tool": "apply_setpoints",
                        "arguments": {
                            "action": {"zone1_heating_setpoint": 20.0, "zone1_cooling_setpoint": 25.0},
                        },
                    },
                }
            elif "Tool Result for propose_setpoints" in messages_text:
                # Turn 2: LLM calls validate_action
                response_content = {
                    "thought": "Candidate setpoints generated by optimizer. Now invoking validate_action to check safety bounds.",
                    "tool_call": {
                        "tool": "validate_action",
                        "arguments": {
                            "candidate": {"zone1_heating_setpoint": 20.0, "zone1_cooling_setpoint": 25.0},
                        },
                    },
                }
            else:
                # Turn 1: LLM calls propose_setpoints
                response_content = {
                    "thought": "Observed zone telemetry. Invoking propose_setpoints with balanced energy/comfort weighting.",
                    "tool_call": {
                        "tool": "propose_setpoints",
                        "arguments": {
                            "objective_weights": {"w_energy": 0.5, "w_comfort_penalty": 0.5},
                            "horizon_steps": 4,
                        },
                    },
                }

            payload = {
                "id": "chatcmpl-mock123",
                "object": "chat.completion",
                "created": 1700000000,
                "model": "qwen2.5-7b-instruct",
                "choices": [
                    {
                        "index": 0,
                        "message": {
                            "role": "assistant",
                            "content": json.dumps(response_content),
                        },
                        "finish_reason": "stop",
                    }
                ],
            }

            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps(payload).encode("utf-8"))
        else:
            self.send_error(404, "Not Found")

    def log_message(self, format, *args):
        pass


def run_server():
    server = HTTPServer(("127.0.0.1", PORT), MockLLMHandler)
    print(f"Mock LLM Server running at http://127.0.0.1:{PORT}/v1")
    server.serve_forever()


if __name__ == "__main__":
    run_server()
